<definitions
  targetNamespace = "http://www.examples.com/wsdl/Court_Service.wsdl"
  xmlns = "http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
  name = "Court_Service"
  xmlns:tns = "http://www.examples.com/wsdl/Court_Service.wsdl"
  xmlns:xsd = "http://www.w3.org/2001/XMLSchema" >
   <message name = "CheckCarRequest">
      <part name = "plateNumber" type = "xsd:string"/>
   </message>
   <message name = "CheckCarResponse">
      <part name = "status" type = "xsd:string"/>
   </message>
   <portType name = "Court_Data_PortType">
      <operation name = "CheckCar">
         <input message = "tns:CheckCarRequest"/>
         <output message = "tns:CheckCarResponse"/>
      </operation>
   </portType>
   <binding name = "CheckCar_Binding" type = "tns:Court_Data_PortType">
      <soap:binding style = "rpc"
         transport = "http://schemas.xmlsoap.org/soap/http"/>
      <operation name = "CheckCar">
         <soap:operation soapAction = "CheckCar"/>
         <input>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:Court_Service" use = "encoded"/>
         </input>
         <output>
            <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/" namespace = "urn:examples:Court_Service" use = "encoded"/>
         </output>
      </operation>
   </binding>
   <service name = "Court_Service">
      <documentation>WSDL File for Court_Service</documentation>
      <port binding = "tns:CheckCar_Binding" name = "Court_Data_PortType">
         <soap:address
            location = "http://localhost:8001/wsdl" />
      </port>
   </service>
</definitions>